### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by UpadhyayPooja** [aj-medianet/icalgenerator#1]
Hi... I want to use this....but it is having issue in IE [demo url](https://icalgenerator.net/) is not even opening in IE. its working fine in Edge. @aj-medianet could you help please.

**Comment by aj-medianet** [comment]
React doesn’t work in IE out of the box. 

here’s a SO article about it. You can make it work in IE but you’ll have to add some tweaks. 

https://stackoverflow.com/questions/53631949/why-ie-11-display-blank-page-rendering-react-app
